export const BUSINESS_TYPES = {
    SARI_SARI: 'SARI_SARI',
    FOOD_AND_BEVERAGE: 'FOOD_AND_BEVERAGE',
    BAKERY: 'BAKERY',
    PHARMACY: 'PHARMACY',
    MINI_GROCERY: 'MINI_GROCERY',
    HARDWARE: 'HARDWARE',
    VAPE_SHOP: 'VAPE_SHOP',
    GENERAL: 'GENERAL',
} as const;

export type BusinessType = typeof BUSINESS_TYPES[keyof typeof BUSINESS_TYPES];

export const BUSINESS_TYPE_INFO = {
    [BUSINESS_TYPES.SARI_SARI]: {
        name: 'Sari-Sari Store',
        description: 'Perfect for small neighborhood stores selling everyday essentials',
        icon: '🏪',
        categories: ['Beverages', 'Canned Goods', 'Snacks', 'Toiletries', 'Household Items', 'Cigarettes'],
        showPackages: false,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: false, label: '', percentage: 0 },
    },
    [BUSINESS_TYPES.FOOD_AND_BEVERAGE]: {
        name: 'Food & Beverage',
        description: 'Ideal for restaurants, cafes, carinderias, and food stalls',
        icon: '🍔',
        categories: ['Beverages', 'Main Dishes', 'Sides', 'Desserts', 'Appetizers', 'Combos'],
        showPackages: true,
        emphasizeCostTracking: false,
        additionalCharge: { enabled: true, label: 'Service Charge', percentage: 10 },
    },
    [BUSINESS_TYPES.BAKERY]: {
        name: 'Bakery / Pastry Shop',
        description: 'For bakeries selling bread, pastries, cakes, and baked goods',
        icon: '🍞',
        categories: ['Breads', 'Pastries', 'Cakes', 'Cookies', 'Beverages', 'Special Orders'],
        showPackages: true,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: false, label: '', percentage: 0 },
    },
    [BUSINESS_TYPES.PHARMACY]: {
        name: 'Pharmacy / Drugstore',
        description: 'For pharmacies and drugstores selling medicines and health products',
        icon: '💊',
        categories: ['Prescription Drugs', 'OTC Medicines', 'Vitamins', 'First Aid', 'Personal Care', 'Health Devices'],
        showPackages: false,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: true, label: 'Professional Fee', percentage: 5 },
    },
    [BUSINESS_TYPES.MINI_GROCERY]: {
        name: 'Mini Grocery / Supermarket',
        description: 'For small grocery stores and mini-marts with varied inventory',
        icon: '🛒',
        categories: ['Fresh Produce', 'Meat & Poultry', 'Dairy', 'Canned Goods', 'Beverages', 'Household'],
        showPackages: false,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: false, label: '', percentage: 0 },
    },
    [BUSINESS_TYPES.HARDWARE]: {
        name: 'Hardware Store',
        description: 'For hardware stores selling construction materials and tools',
        icon: '🔨',
        categories: ['Tools', 'Construction Materials', 'Electrical', 'Plumbing', 'Paint', 'Supplies'],
        showPackages: false,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: true, label: 'Professional Fee', percentage: 3 },
    },
    [BUSINESS_TYPES.VAPE_SHOP]: {
        name: 'Vape Shop',
        description: 'For vape and e-cigarette stores selling vaping products',
        icon: '💨',
        categories: ['Vape Devices', 'E-Liquids', 'Pods & Coils', 'Accessories', 'Batteries', 'Starter Kits'],
        showPackages: true,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: false, label: '', percentage: 0 },
    },
    [BUSINESS_TYPES.GENERAL]: {
        name: 'General / Other',
        description: 'Versatile setup for mixed or specialized businesses',
        icon: '⚙️',
        categories: ['Products', 'Services', 'Merchandise', 'Supplies'],
        showPackages: true,
        emphasizeCostTracking: true,
        additionalCharge: { enabled: false, label: '', percentage: 0 },
    },
};
